# $\cos3\phi$

In [13]:
import scqubits as scq
import matplotlib.pyplot as plt
import numpy as np
import qutip as qt

### Construct circuit

<img src="../image/cos3phi-2.png" alt="drawing" align="left" width="400"/>


In [23]:
cos3phi_yaml ="""
# zero-pi circuit
branches:
- ["JJ", 1, 2, Ej=6, Ecj=2.28] 
- ["JJ", 3, 4, Ej, Ecj]
- ["L", 2, 3, EL=0.38]
- ["L", 1, 4, EL]
- ["C", 1, 3, Ec=0.20]
- ["C", 2, 4, Ec]

- ["C", 1, 5, Ec]
- ["L", 2, 5, EL]
- ["C", 2, 6, Ec]
- ["L", 1, 6, EL]
- ["JJ", 5, 6, Ej, Ecj]
"""

### Default transform

In [24]:
cos3phi = scq.Circuit(cos3phi_yaml, from_file=False)
cos3phi.sym_hamiltonian()
print(cos3phi.var_categories)
print(cos3phi.cutoff_names)
print(cos3phi.variable_transformation())
qt.Qobj(np.linalg.inv(cos3phi.transformation_matrix))

<IPython.core.display.Latex object>

{'periodic': [1], 'extended': [2, 3, 4, 5], 'free': [], 'frozen': []}
['cutoff_n_1', 'cutoff_ext_2', 'cutoff_ext_3', 'cutoff_ext_4', 'cutoff_ext_5']


<IPython.core.display.Latex object>

None


Quantum object: dims = [[6], [6]], shape = (6, 6), type = oper, isherm = False
Qobj data =
[[-1.    1.    0.    0.    0.    0.  ]
 [ 0.   -0.5   0.25 -0.25  0.25  0.25]
 [ 0.    0.   -0.25 -0.25  0.25  0.25]
 [ 1.   -1.    0.5  -0.5   0.5  -0.5 ]
 [ 0.    0.    0.5  -0.5  -0.5   0.5 ]
 [ 0.    0.5  -0.5   1.    0.    0.  ]]

In [31]:
qt.Qobj(cos3phi.transformation_matrix)

Quantum object: dims = [[6], [6]], shape = (6, 6), type = oper, isherm = False
Qobj data =
[[-0.5  -0.5   0.5   0.5   0.    0.  ]
 [ 0.5   0.5   0.5   0.5   0.    0.  ]
 [-0.5   0.5  -0.25  0.25  0.    0.5 ]
 [ 0.5  -0.5  -0.25  0.25  0.    0.5 ]
 [ 0.5  -0.5   0.25 -0.25  1.    0.5 ]
 [-0.5   0.5   0.25 -0.25 -1.    0.5 ]]

In [ ]:
# tm5 = np.array([[-1.,  1.,  1., -1.,  1., -1.],
#                 [-1.,  1., -1.,  1.,  1., -1.],
#                 [-1.,  1.,  1., -1., -1.,  1.],
#                 [ 1., -1.,  1., -1.,  1., -1.],
#                 [ 1.,  1., -1., -1., -1., -1.],
#                 [ 1.,  1.,  1.,  1.,  1.,  1.]])
# np.linalg.inv(tm5)

### Custom transform

In [29]:
tm = np.array([
       [-0.5,  0.5, -0.5,  0.5,  0.,  0. ],
       [-0.5,  0.5,  0.5, -0.5,  0.,  0. ],
       [ 0.5,  0.5, -0.5, -0.5,  0.,  0. ],
       [ 0.5,  0.5,  0.5,  0.5,  0.,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  1., -1. ],
       [ 1. ,  1. ,  1. ,  1. ,  1.,  1. ]])
cos3phi = scq.Circuit(cos3phi_yaml, from_file=False)
cos3phi.configure(transformation_matrix=np.linalg.inv(tm))
cos3phi.sym_hamiltonian()
print(cos3phi.var_categories)
print(cos3phi.cutoff_names)

<IPython.core.display.Latex object>

{'periodic': [], 'extended': [1, 2, 3, 4, 5, 6], 'free': [], 'frozen': []}
['cutoff_ext_1', 'cutoff_ext_2', 'cutoff_ext_3', 'cutoff_ext_4', 'cutoff_ext_5', 'cutoff_ext_6']


In [30]:
tm= np.array([
       [-0.5,  0.5, -0.5,  0.5,  0.,  0. ],
       [-0.5,  0.5,  0.5, -0.5,  0.,  0. ],
       [ 0.5,  0.5, -0.5, -0.5, 0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,-0.5, -0.5],
       [ 0. ,  0. ,  0.5, -0.5, 0.5, -0.5],
       [ 0. ,  0. ,  0.5,  0.5, 0.5, 0.5]])
cos3phi = scq.Circuit(cos3phi_yaml, from_file=False)
cos3phi.configure(transformation_matrix=np.linalg.inv(tm))
cos3phi.sym_hamiltonian()
print(cos3phi.var_categories)
print(cos3phi.cutoff_names)


 C:\Users\Zhenxing Liu\AppData\Roaming\Python\Python310\site-packages\scqubits\core\symbolic_circuit.py: 1007

<IPython.core.display.Latex object>

{'periodic': [], 'extended': [1, 2, 3, 4, 5, 6], 'free': [], 'frozen': []}
['cutoff_ext_1', 'cutoff_ext_2', 'cutoff_ext_3', 'cutoff_ext_4', 'cutoff_ext_5', 'cutoff_ext_6']


# $\cos3\phi$ part #2

<img src="../image/cos3phi-3.png" alt="drawing" align="left" width="500"/>


In [33]:
cos3phi_yaml ="""
# zero-pi circuit
branches:
- ["JJ", 1, 2, Ej=6, Ecj=2.28] 
- ["JJ", 3, 4, Ej, Ecj]
- ["L", 2, 3, EL=0.38]
- ["L", 1, 4, EL]
- ["C", 1, 3, Ec=0.20]
- ["C", 2, 4, Ec]

- ["C", 3, 5, Ec]
- ["L", 4, 5, EL]
- ["C", 4, 6, Ec]
- ["L", 3, 6, EL]
- ["JJ", 5, 6, Ej, Ecj]

- ["L", 2, 6, EL]
- ["L", 1, 5, EL]
- ["C", 1, 6, Ec]
- ["C", 2, 5, Ec]
"""

cos3phi = scq.Circuit(cos3phi_yaml, from_file=False, ext_basis="discretized")
#zp3.configure(transformation_matrix=np.linalg.inv(tm3))
cos3phi.sym_hamiltonian()
print(cos3phi.var_categories)
print(cos3phi.cutoff_names)
print(cos3phi.variable_transformation())
qt.Qobj(np.linalg.inv(cos3phi.transformation_matrix))

<IPython.core.display.Latex object>

{'periodic': [1], 'extended': [2, 3, 4, 5], 'free': [], 'frozen': []}
['cutoff_n_1', 'cutoff_ext_2', 'cutoff_ext_3', 'cutoff_ext_4', 'cutoff_ext_5']


<IPython.core.display.Latex object>

None


Quantum object: dims = [[6], [6]], shape = (6, 6), type = oper, isherm = False
Qobj data =
[[-1.    1.    0.    0.    0.    0.  ]
 [ 0.   -0.5   0.25 -0.25  0.25  0.25]
 [ 0.    0.   -0.25 -0.25  0.25  0.25]
 [ 0.    0.    0.5  -0.5   0.5  -0.5 ]
 [ 1.   -1.    0.5  -0.5  -0.5   0.5 ]
 [ 0.    0.5  -0.5   1.    0.    0.  ]]

In [34]:
qt.Qobj(cos3phi.transformation_matrix)

Quantum object: dims = [[6], [6]], shape = (6, 6), type = oper, isherm = False
Qobj data =
[[ 0. -1.  1.  1.  1.  1.]
 [ 1. -1.  1.  1.  1.  1.]
 [ 1.  1. -1.  1.  1.  1.]
 [ 0.  1. -1.  0.  0.  1.]
 [ 0.  1.  1.  1.  0.  1.]
 [ 1.  1.  1.  0.  1.  1.]]

In [12]:
# Cholesky transformation 
Ecj = 2.28
Ec = 0.20

transform = np.array([
       [-0.5,  0.5, -0.5,  0.5, -0.5,  0.5 ],
       [-0.5,  0.5,  0.5, -0.5, -0.5,  0.5 ],
       [ 0.5,  0.5,  0.5, -0.5, -0.5, -0.5 ],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5 ],
       [   0,    0,    0,    0,    1,   0  ],
       [   1,    -Ec/(Ec+Ecj),    -Ecj/(Ec+Ecj),    0,    0,   0 ]])
cos3phi = scq.Circuit(cos3phi_yaml, from_file=False, ext_basis="discretized")
cos3phi.configure(transformation_matrix=np.linalg.inv(transform))
cos3phi.sym_hamiltonian()

cos3phi.variable_transformation()

cos3phi.var_categories


 C:\Users\Zhenxing Liu\AppData\Roaming\Python\Python310\site-packages\scqubits\core\symbolic_circuit.py: 1007

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

{'periodic': [], 'extended': [1, 2, 3, 4, 5, 6], 'free': [], 'frozen': []}

In [ ]:
# Cholesky transformation 
Ecj = 2.28
Ec = 0.20

transform = np.array([
    [   1,    -Ec/(Ec+Ecj),    -Ecj/(Ec+Ecj),    0,    0,   0 ],
       [0,  1, 0,  0, 0,  0 ],
       [0,  0, 1,  0, 0,  0 ],
       [0,  0, 0,  1, 0,  0 ],
       [0,  0, 0,  0, 1,  0 ],
       [0,  0, 0,  0, 0,  1  ],
       ])
cos3phi = scq.Circuit(cos3phi_yaml, from_file=False, ext_basis="discretized")
cos3phi.configure(transformation_matrix=np.linalg.inv(transform))
cos3phi.sym_hamiltonian()

cos3phi.variable_transformation()

cos3phi.var_categories